# Generated by Django 4.2.4 on 2024-02-14 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], max_length=5)),
                ('event_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], max_length=10)),
                ('class_name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flames24_app.department')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flames24_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_points', models.IntegerField(default=0)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flames24_app.department')),
            ],
        ),
    ]
