# Generated by Django 4.2.4 on 2024-02-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flames24_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
