# Generated by Django 4.2.4 on 2024-02-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flames24_app', '0002_alter_department_dept_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
