# Generated by Django 4.2.4 on 2024-02-14 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flames24_app', '0003_winner_points'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('event_name', 'event_type')},
        ),
    ]
