# Generated by Django 4.2.4 on 2024-02-14 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flames24_app', '0004_alter_event_unique_together'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='Department',
        ),
        migrations.AlterModelTable(
            name='departmentresult',
            table='DepartmentResult',
        ),
        migrations.AlterModelTable(
            name='event',
            table='Events',
        ),
        migrations.AlterModelTable(
            name='winner',
            table='Winner',
        ),
    ]
