# Generated by Django 4.2.4 on 2024-02-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flames24_app', '0005_alter_department_table_alter_departmentresult_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='winner_athlete',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='winner',
            unique_together={('event', 'winner_athlete', 'position')},
        ),
    ]
