# Generated by Django 4.2.4 on 2024-02-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flames24_app', '0006_winner_winner_athlete_alter_winner_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=100, unique=True)),
                ('image_url', models.URLField()),
            ],
        ),
    ]
